version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - ./config:/etc/selenoid # assumed current dir contains browsers.json
      - /var/run/docker.sock:/var/run/docker.sock
      - ./output/logs:/opt/selenoid/logs
    command: ["--conf", "/etc/selenoid/browsers.json",  "-log-output-dir", "/opt/selenoid/logs"]


  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

  android_7:
    image: "selenoid/android:7.0"
    container_name: Android
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui

  Chrome-VNC:
    image: "selenoid/vnc_chrome:104.0"
    container_name: Chrome
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
  
  Fiefox-VNC:
    image: "selenoid/vnc_firefox:103.0"
    container_name: Firefox
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui

  Chrome-Mobile:
    image: "selenoid/chrome-mobile:86.0"
    container_name: ChromeMobile
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui


