package com.ctfs.api.utils;

public enum AtomicServices  {
	
	ACCOUNTSERVICE("ACCOUNTSERVICE_V1"),
	ADDRESSSERVICE("ADDRESSSERVICE_V1"),
	ADJUDICATIONCONTROLLER("ADJUDICATIONCONTROLLER_V1"),
	ADMSERVICE("ADMSERVICE_V1"),
	BANKACQUISITIONCONTROLLER("BANKACQUISITIONCONTROLLER_V1"),
	BANKCONTROLLER("BANKCONTROLLER_V1"),
	BANKENROLLCONTROLLER("BANKENROLLCONTROLLER_V1"),
	BATCHCONTROLLER("BATCHCONTROLLER_V1"),
	BILLPAYMENTSERVICE("BILLPAYMENTSERVICE_V1"),
	BRBWSSERVICE("BRBWSSERVICE_V1"),
	CALLCENTRECONTROLLER("CALLCENTRECONTROLLER_V1"),
	CALLERAUTHENTICATESERVICE("CALLERAUTHENTICATESERVICE_V1"),
	CARDACTIVATIONCONTROLLER("CARDACTIVATIONCONTROLLER_V1"),
	CARDGUARDSERVICE("CARDGUARDSERVICE_V1"),
	CERTIFICATESERVICE("CERTIFICATESERVICE_V1"),
	COLLECTIONSCONTROLLER("COLLECTIONSCONTROLLER_V1"),
	CTFSDIRECTORYSERVICE("CTFSDIRECTORYSERVICE_V1"),
	CUSTOMERCONTACTSERVICE("CUSTOMERCONTACTSERVICE_V1"),
	DASHCONTROLLER("DASHCONTROLLER_V1"),
	DASHENROLLCONTROLLER("DASHENROLLCONTROLLER_V1"),
	DIRECTORYSERVICE("DIRECTORYSERVICE_V1"),
	DOCUMENTARCHIVESERVICE("DOCUMENTARCHIVESERVICE_V1"),
	EBVSSERVICE("EBVSSERVICE_V1"),
	EMPLOYEEAPPSERVICE_V1("EMPLOYEEAPPSERVICE_V1"),
	FRAUDPREVENTIONSERVICE("FRAUDPREVENTIONSERVICE_V1"),
	GATEWAYSERVICEA("GATEWAYSERVICE-A"),
	GATEWAYSERVICEB("GATEWAYSERVICE-B"),
	IDENTITYSERVICE("IDENTITYSERVICE_V1"),
	INSTANTCREDITSERVICE("INSTANTCREDITSERVICE_V1"),
	INTERACTIONHISTORYSRVC("INTERACTIONHISTORYSRVC_V1"),
	IVRCONTROLLER("IVRCONTROLLER_V1"),
	KOFAXSERVICE("KOFAXSERVICE_V1"),
	LOYALTYSERVICE("LOYALTYSERVICE_V1"),
	LOYALTYSERVICEV2("LOYALTYSERVICE_V2"),
	MDESSERVICE("MDESSERVICE_V1"),
	MESSAGESERVICE("MESSAGESERVICE_V1"),
	MOBILECONTROLLER("MOBILECONTROLLER_V1"),
	NOTIFYMESERVICE("NOTIFYMESERVICE_V1"),
	OFFERSERVICE("OFFERSERVICE_V1"),
	PAYMENTGATEWAYSERVICE("PAYMENTGATEWAYSERVICE_V1"),
	PEGABACKOFFICESERVICE("PEGABACKOFFICESERVICE_V1"),
	PEGACALLCENTRECONTROLLERFEATUREPEGASD("PEGACALLCENTRECONTROLLER-FEATUREPEGASD_V1"),
	PEGACALLCENTRECONTROLLER("PEGACALLCENTRECONTROLLER_V1"),
	PINSERVICE("PINSERVICE_V1"),
	PRODUCTSERVICE("PRODUCTSERVICE_V1"),
	REGISTRYSERVICE("REGISTRYSERVICE"),
	SASIDSERVICE("SASIDSERVICE_V1"),
	SDDSERVICE("SDDSERVICE_V1"),
	SERVICEHISTORYSERVICE("SERVICEHISTORYSERVICE_V1"),
	TELUSWBSERVICE("TELUSWBSERVICE_V1"),
	THREATMETRIXSERVICE("THREATMETRIXSERVICE_V1"),
	TRANSACTIONSERVICE("TRANSACTIONSERVICE_V1"),
	TS2SERVICEFEATUREPEGASD("TS2SERVICE-FEATUREPEGASD_V1"),
	TS2SERVICE("TS2SERVICE_V1"),
	TSYSALERTSERVICE("TSYSALERTSERVICE_V1"),
	TSYSCOMMSSERVICE("TSYSCOMMSSERVICE_V1"),
	USERPROFILESERVICE("USERPROFILESERVICE_V1"),
	SECUREKEY("SECUREKEYSERVICE_V1"),
	UTILITYSERVICE("UTILITYSERVICE_V1"), MASTERCARDSERVICE("MASTERCARDSERVICE_V1");	

    public final String GetApplicationName;
//    public final String portNbr ; 

    AtomicServices(String serviceName) {
        
        this.GetApplicationName = serviceName;
//        this.portNbr = AtomicServiceUtils.getPort(GetApplicationName);
    }
   
//    public static String getPort(String service) {
//		for (AtomicServices atomic : AtomicServices.values()) {
//			if(atomic.GetApplicationName.equals(service)) return atomic.portNbr;
//		}
//		return "no port number detected";
//	}

}
